/**
 * seed-user.js -- Generated by Claude
 *
 * Dev-only helper to fill a user's vault (jobs, education, projects,
 * optionally a resume) with realistic dummy data, so you're not
 * hand-typing test records every time.
 *
 * Usage:
 *   node seed-user.js --email test@test.com
 *   node seed-user.js --email test@test.com --create            (create the user if it doesn't exist)
 *   node seed-user.js --email test@test.com --create --password mypassword
 *   node seed-user.js --email test@test.com --clear              (wipe that user's existing jobs/education/projects first)
 *   node seed-user.js --email test@test.com --clear --create
 *
 * Notes:
 *   - Looks up the user by email in tblUsers. If not found:
 *       - with --create: registers a new user (bcrypt-hashed password, default "password123")
 *       - without --create: exits with an error so you don't accidentally seed the wrong thing
 *   - Uses the SAME db path logic as server.js (project root database.db when not
 *     running under Electron). If you're testing the packaged Electron app instead,
 *     point --db at the userData database.db, e.g.:
 *       node seed-user.js --email test@test.com --db "/path/to/database.db"
 *   - Safe to run repeatedly; --clear only deletes jobs/education/projects/resumes
 *     for THAT user, never touches other users or the users table itself.
 */

const path = require('path')
const sqlite3 = require('sqlite3')
const bcrypt = require('bcrypt')
const { v4: uuidv4 } = require('uuid')

// --- tiny arg parser ---
function parseArgs(argv) {
    const args = { create: false, clear: false }
    for (let i = 0; i < argv.length; i++) {
        const a = argv[i]
        if (a === '--email') args.email = argv[++i]
        else if (a === '--password') args.password = argv[++i]
        else if (a === '--db') args.db = argv[++i]
        else if (a === '--create') args.create = true
        else if (a === '--clear') args.clear = true
        else if (a === '--help' || a === '-h') args.help = true
    }
    return args
}

const args = parseArgs(process.argv.slice(2))

if (args.help || !args.email) {
    console.log(`
Usage: node seed-user.js --email <email> [--create] [--password <pw>] [--clear] [--db <path>]

  --email       Required. The user to seed dummy data for.
  --create      Create the user if they don't already exist.
  --password    Password to use when creating the user (default: "password123").
  --clear       Delete this user's existing jobs/education/projects/resumes before seeding.
  --db          Path to database.db (default: same path server.js uses in non-Electron mode).
`)
    process.exit(args.help ? 0 : 1)
}

const dbPath = args.db || path.join(__dirname, 'database.db')
console.log(`Using database: ${dbPath}`)

const db = new sqlite3.Database(dbPath, (err) => {
    if (err) {
        console.error(`Could not open database: ${err.message}`)
        process.exit(1)
    }
})

// promisified helpers
const run = (sql, params = []) => new Promise((resolve, reject) => {
    db.run(sql, params, function (err) { err ? reject(err) : resolve(this) })
})
const get = (sql, params = []) => new Promise((resolve, reject) => {
    db.get(sql, params, (err, row) => err ? reject(err) : resolve(row))
})

// --- dummy data generators ---

const DUMMY_JOBS = [
    {
        company: 'Nimbus Analytics',
        location: 'Austin, TX',
        role: 'Senior Software Engineer',
        start_date: '2022-03',
        end_date: 'Present',
        description: '<ul><li>Led migration of monolithic billing service to microservices, cutting deploy time by 40%</li><li>Mentored 3 junior engineers and ran weekly code review sessions</li><li>Built internal dashboard used by 50+ engineers to monitor API latency</li></ul>'
    },
    {
        company: 'Brightleaf Software',
        location: 'Remote',
        role: 'Software Engineer',
        start_date: '2019-06',
        end_date: '2022-02',
        description: '<ul><li>Developed customer-facing REST API handling 2M+ requests/day</li><li>Reduced page load times by 35% through caching and query optimization</li><li>Collaborated with design team to ship a redesigned onboarding flow</li></ul>'
    },
    {
        company: 'Cedarwood Retail Co.',
        location: 'Denver, CO',
        role: 'Junior Developer',
        start_date: '2017-08',
        end_date: '2019-05',
        description: '<ul><li>Maintained internal inventory management tools written in Node.js</li><li>Fixed cross-browser bugs across legacy jQuery codebase</li><li>Wrote automated test suite that caught regressions pre-release</li></ul>'
    }
]

const DUMMY_EDUCATION = [
    {
        school_name: 'University of Colorado Boulder',
        degree: 'Bachelor of Science',
        major: 'Computer Science',
        minor: 'Mathematics',
        gpa: '3.7',
        location: 'Boulder, CO',
        start_date: '2013-08',
        end_date: '2017-05',
        description: 'Relevant coursework: Data Structures, Distributed Systems, Databases. Dean\'s List x4.'
    }
]

const DUMMY_PROJECTS = [
    {
        title: 'RouteOptimizer',
        description: 'Open-source CLI tool that computes optimal delivery routes using a modified Dijkstra\'s algorithm. Supports CSV import/export and live traffic weighting.',
        tech_stack: 'Python, NetworkX, Click',
        link: 'https://github.com/example/route-optimizer',
        proj_date: '2023-05'
    },
    {
        title: 'PantryPal',
        description: 'Mobile-friendly web app for tracking pantry inventory and suggesting recipes based on what\'s about to expire. Built as a weekend hackathon project.',
        tech_stack: 'React, Node.js, SQLite',
        link: 'https://github.com/example/pantry-pal',
        proj_date: '2021-11'
    }
]

const DUMMY_PROFILE = {
    full_name: 'Jamie Rivera',
    skills: 'JavaScript, Node.js, React, SQL, Python, Docker, AWS, REST APIs, Git',
    phone: '555-0142',
    linkedin_url: 'https://linkedin.com/in/example',
    github_url: 'https://github.com/example',
    summary: 'Full-stack engineer with 7+ years of experience building scalable web applications, from backend APIs to polished front-end UIs. Enjoys mentoring and cross-functional collaboration.'
}

async function findOrCreateUser(email) {
    let user = await get('SELECT id, full_name FROM tblUsers WHERE email = ?', [email])
    if (user) {
        console.log(`Found existing user: ${email} (id: ${user.id})`)
        return user
    }

    if (!args.create) {
        console.error(`No user found with email "${email}". Re-run with --create to make one, or register them in the app first.`)
        process.exit(1)
    }

    const password = args.password || 'password123'
    const userId = uuidv4()
    const passwordHash = bcrypt.hashSync(password, 12)

    await run('INSERT INTO tblUsers (id, email, password_hash) VALUES (?, ?, ?)', [userId, email, passwordHash])
    console.log(`Created new user: ${email} (id: ${userId}, password: ${password})`)
    return { id: userId, full_name: null }
}

async function fillProfile(userId) {
    await run(
        `UPDATE tblUsers SET full_name = ?, skills = ?, phone = ?, linkedin_url = ?, github_url = ?, summary = ? WHERE id = ?`,
        [DUMMY_PROFILE.full_name, DUMMY_PROFILE.skills, DUMMY_PROFILE.phone, DUMMY_PROFILE.linkedin_url, DUMMY_PROFILE.github_url, DUMMY_PROFILE.summary, userId]
    )
    console.log('Filled profile fields.')
}

async function clearExistingData(userId) {
    await run('DELETE FROM tblJobs WHERE user_id = ?', [userId])
    await run('DELETE FROM tblEducation WHERE user_id = ?', [userId])
    await run('DELETE FROM tblProjects WHERE user_id = ?', [userId])
    await run('DELETE FROM tblResumes WHERE user_id = ?', [userId])
    console.log('Cleared existing jobs/education/projects/resumes for this user.')
}

async function seedJobs(userId) {
    for (const job of DUMMY_JOBS) {
        await run(
            `INSERT INTO tblJobs (id, user_id, company, location, role, start_date, end_date, description) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
            [uuidv4(), userId, job.company, job.location, job.role, job.start_date, job.end_date, job.description]
        )
    }
    console.log(`Inserted ${DUMMY_JOBS.length} jobs.`)
}

async function seedEducation(userId) {
    for (const edu of DUMMY_EDUCATION) {
        await run(
            `INSERT INTO tblEducation (id, user_id, school_name, degree, major, minor, gpa, location, start_date, end_date, description) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
            [uuidv4(), userId, edu.school_name, edu.degree, edu.major, edu.minor, edu.gpa, edu.location, edu.start_date, edu.end_date, edu.description]
        )
    }
    console.log(`Inserted ${DUMMY_EDUCATION.length} education record(s).`)
}

async function seedProjects(userId) {
    for (const proj of DUMMY_PROJECTS) {
        await run(
            `INSERT INTO tblProjects (id, user_id, title, description, tech_stack, link, proj_date) VALUES (?, ?, ?, ?, ?, ?, ?)`,
            [uuidv4(), userId, proj.title, proj.description, proj.tech_stack, proj.link, proj.proj_date]
        )
    }
    console.log(`Inserted ${DUMMY_PROJECTS.length} project(s).`)
}

async function main() {
    try {
        const user = await findOrCreateUser(args.email)

        if (args.clear) {
            await clearExistingData(user.id)
        }

        await fillProfile(user.id)
        await seedJobs(user.id)
        await seedEducation(user.id)
        await seedProjects(user.id)

        console.log(`\nDone. "${args.email}" now has a full dummy vault (profile, ${DUMMY_JOBS.length} jobs, ${DUMMY_EDUCATION.length} education, ${DUMMY_PROJECTS.length} projects).`)
    } catch (err) {
        console.error('Seeding failed:', err)
        process.exitCode = 1
    } finally {
        db.close()
    }
}

main()